# k8s/production/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        deployment: standard  # Add unique label to avoid conflicts
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100  # Required field (1-100)
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["api"]
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: api
          image: my-backend-project-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: UV_THREADPOOL_SIZE
              value: "64"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=256"
            - name: MONGO_URI
              value: "mongodb://host.docker.internal:27017/app"
            - name: REDIS_URL
              value: "redis://host.docker.internal:6379"
            - name: JWT_SECRET
              value: "your_jwt_secret_key"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "development"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 5
            timeoutSeconds: 3        # Increased from 1
            failureThreshold: 5
