# k8s/production/overdrive.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-overdrive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-overdrive  # Changed to unique label
  template:
    metadata:
      labels:
        app: api-overdrive  # Unique label for overdrive pods
        deployment: overdrive
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100  # Required for preferred anti-affinity
              podAffinityTerm:  # Proper nesting
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["api-overdrive"]  # Match the updated label
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: api
          image: my-backend-project-app:latest
          imagePullPolicy: Never
          env:
            - name: UV_THREADPOOL_SIZE
              value: "64"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=8192"
            - name: MONGO_URI
              value: "mongodb://host.docker.internal:27017/app"
            - name: REDIS_URL
              value: "redis://host.docker.internal:6379"
            - name: JWT_SECRET
              value: "your_jwt_secret_key"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "development"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "1024Mi"
