# k8s/production/service.yml
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api  # Or use "deployment: standard" if you update labels
    # deployment: standard
    # Add more specific labels if needed
  ports:
    - port: 3000
      targetPort: 3000
